<?php

return [
    'CLIENT_ID' => env('ETSY_CLIENT_ID', NULL),
    'CLIENT_SECRET' => env('ETSY_CLIENT_SECRET', NULL),
    'INSTALLATION_REDIRECT_URL' => env('ETSY_INSTALLATION_REDIRECT_URL', NULL)
];